GET https://dev.dawidkomeza.pl/api/
Host: dev.dawidkomeza.pl
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNkYWNhMDlhYjI4ZWViOGQyNGNkM2RiIiwiZW1haWwiOiJkYXdpZC5rb21lemFAZ21haWwuY29tIiwiaWF0IjoxNjc1MjgzNDAwLCJleHAiOjE2NzUyOTA2MDB9.SP45gXA2-pcedp1rlMeATVX0eEO6FL1whFItTXa_-dE

######

POST https://dev.dawidkomeza.pl/api/signup
Host: dev.dawidkomeza.pl
Content-Type: application/json

{
    "name": "John Doe",
    "email": "dawid.komeza@gmail.com",
    "password": "password"
}

######

POST https://dev.dawidkomeza.pl/api/login
Host: dev.dawidkomeza.pl
Content-Type: application/json

{
    "email": "dawid.komeza@gmail.com",
    "password": "password"
}

######

POST https://dev.dawidkomeza.pl/api/deleteUser
Host: dev.dawidkomeza.pl
Content-Type: application/json

{
    "email": "dawid.komeza@gmail.com"
}

######

GET dev.dawidkomeza.pl/api/status
