GET https://dev.dawidkomeza.pl/api/
Host: dev.dawidkomeza.pl
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNkYWNhMDlhYjI4ZWViOGQyNGNkM2RiIiwiZW1haWwiOiJkYXdpZC5rb21lemFAZ21haWwuY29tIiwiaWF0IjoxNjc1MzM5OTAxLCJleHAiOjE2NzUzNDcxMDF9.dHVMGGiqNqzPEbJRS-FvsPaFkURXrE-fDCP3jlDRmxk

######

POST https://dev.dawidkomeza.pl/api/signup
Host: dev.dawidkomeza.pl
Content-Type: application/json

{
    "name": "John Doe",
    "email": "dawid.komeza@gmail.com",
    "password": "password"
}

######

POST https://dev.dawidkomeza.pl/api/login
Host: dev.dawidkomeza.pl
Content-Type: application/json

{
    "email": "dawid.komeza@gmail.com",
    "password": "password"
}

######

POST https://dev.dawidkomeza.pl/api/deleteUser
Host: dev.dawidkomeza.pl
Content-Type: application/json

{
    "email": "super@super"
}

######

GET dev.dawidkomeza.pl/api/status
